---
- name: Deploy Apache Docker Container
  hosts: sandy0355
  become: true
  tasks:
    - name: Pull Apache Docker image
      docker_image:
        name: httpd
        source: pull

    - name: Run Apache Docker container
      docker_container:
        name: apache_container
        image: httpd
        state: started
        ports:
          - "80:80"
